language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade -e .[dev]
script:
  - pytest --cov-report term-missing --cov sqlitemap
  - flake8 sqlitemap tests
  - isort -rc -c --diff sqlitemap tests
after_success:
  - coveralls
